defaults:
  max_enchant_level_default: 10
  max_enchant_level_perm: 30
  level_back: 0.5
  level_cost_per_skill_level: 4
  mult_per_skill_level: 0.0
  max_level_cost: 40
  level_back_mult: 1.0
enchants:
  protection: 0-10
  protect: 0-10
  fireprotection: 1-10
  fireprotect: 1-10
  featherfalling: 2-10
  feather: 2-10
  blastprotect: 3-10
  blastprotection: 3-10
  projectileprotection: 4-10
  projectileprotect: 4-10
  projectile: 4-10
  respiration: 5-10
  aquaaffinity: 6-10
  wateraffinity: 6-10
  thorns: 7-10
  sharpness: 16-10
  sharp: 16-10
  smite: 17-10
  baneofarthropods: 18-10
  arthropods: 18-10
  knockback: 19-10
  fireaspect: 20-10
  looting: 21-10
  loot: 21-10
  efficiency: 32-10
  efficient: 32-10
  silktouch: 33-10
  silk: 33-10
  unbreaking: 34-10
  fortune: 35-10
  power: 48-10
  punch: 49-10
  flame: 50-10
  infinity: 51-10
  infinite: 51-10
  luckofthesea: 61-10
  luck: 61-10
  lure: 62-10
autorefillsettings: {}