defaults:
  max_enchant_level_default: 10
  max_enchant_level_perm: 30
  level_back: 0.5
  level_cost_per_skill_level: 4
  mult_per_skill_level: 0.0
  max_level_cost: 40
enchants:
  protection: 0
  protect: 0
  fireprotection: 1
  fireprotect: 1
  featherfalling: 2
  feather: 2
  blastprotect: 3
  blastprotection: 3
  projectileprotection: 4
  projectileprotect: 4
  projectile: 4
  respiration: 5
  aquaaffinity: 6
  wateraffinity: 6
  sharpness: 16
  sharp: 16
  smite: 17
  baneofarthropods: 18
  arthropods: 18
  knockback: 19
  fireaspect: 20
  looting: 21
  loot: 21
  efficiency: 32
  efficient: 32
  silktouch: 33
  silk: 33
  unbreaking: 34
  fortune: 35
  power: 48
  punch: 49
  flame: 50
  infinity: 51
  infinite: 51
enchantsmaxlevels:
  0: 10
  1: 10
  2: 10
  3: 10
  4: 10
  5: 10
  6: 10
  16: 10
  17: 10
  18: 10
  19: 10
  20: 10
  21: 10
  32: 10
  33: 1
  34: 10
  35: 10
  48: 10
  49: 10
  50: 10
  51: 10
