name: EnchantIt
main: enchantit.EnchantIt
version: 1.0
dev-url: http://http://dev.bukkit.org/server-mods/enchantit/
description: Enchant with levels
commands:
  enchantIt:
    description: EnchantIt Command
    aliases: eit
permissions:
  enchantit:
    description: Permission to use enchantit
  enchantit.enchantmore:
    description: Higher max enchanting level
    default: op
  enchantit.reload:
    description: Reload Config
    default: op
  enchantit.levelback:
    description: Get level back on item destroy
    default: op
  enchantit.decrease:
    description: Can decrease enchantment level
  enchantit.increase:
    description: Can increase enchantment level
  enchantit.refill:
    description: Automatic refilling item in hand if possible