name: EnchantIt
main: enchantit.EnchantIt
version: 1.0
dev-url: http://http://dev.bukkit.org/server-mods/enchantit/
description: Enchant with levels
commands:
  enchantIt:
    description: EnchantIt Command
    aliases: eit
permissions:
  enchantIt.enchantmore:
    description: Higher max enchanting level
    default: op
  enchantIt.reload:
    description: Reload Config
    default: op
  enchantIt.levelback:
    description: Get level back on item destroy
    default: op
  enchantIt.decrease:
    description: Can decrease enchantment level
  enchantIt.increase:
    description: Can increase enchantment level