name: EnchantIt
main: enchantit.EnchantIt
version: 1.0
dev-url: http://http://dev.bukkit.org/server-mods/enchantit/
description: Enchant with levels
commands:
  enchantIt:
    description: EnchantIt Command
    aliases: eit
permissions:
  enchantIt.enchantmore:
    description: Higher max enchanting level
    default: op